---
- name: 'Assert'
  ansible.builtin.include_tasks: 'assert.yml'
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Build'
  when: not jellyseerr_srv_force_config_only_enable
  ansible.builtin.include_tasks: 'build.yml'

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
- name: 'Set owner'
  ansible.builtin.include_tasks: 'set_owner.yml'
- name: 'Validate'
  ansible.builtin.include_tasks: 'validate.yml'
