---
###############################################################################
# Overseerr Prep
###############################################################################
# Prep Overseerr variables for installation and upgrade. Installed from source,
# all configuration is done in the install directory.
#
# Generates:
#   _overseerr_uid: int - overseerr user UID.
#   _overseerr_gid: int - overseerr user GID.
#   _overseerr_service_config: dict - overseerr service configuration.
#
# Reference:
# * https://overseerr.dev/
# * https://github.com/sct/overseerr/
# * https://docs.overseerr.dev/getting-started/installation

- name: 'Prep | manage users'
  when: overseerr_create_user
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_group: '{{ overseerr_role_group }}'
    users_role_user: '{{ overseerr_role_user }}'

- name: 'Prep | enumerate system user {{ overseerr_user }}'
  ansible.builtin.user:
    name: '{{ overseerr_user }}'
  check_mode: true
  changed_when: false
  register: _overseerr_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _overseerr_uid: '{{ _overseerr_user_query.uid }}'
    _overseerr_gid: '{{ _overseerr_user_query.group }}'

- name: 'Prep | build service config'
  ansible.builtin.set_fact:
    _overseerr_service_config: {
      port: '{{ overseerr_config_port | default(5055) }}',
      host: '{{ overseerr_config_bind_address | default("") }}',
    }

# Overseerr isn't packaged; always shutdown in case a new version is released.
- name: 'Prep | stop Overseerr'
  ansible.builtin.service:
    name: 'overseerr'
    state: 'stopped'
  failed_when: false
