---
###############################################################################
# Overseerr Handlers
###############################################################################

- name: 'Handlers | restart overseerr'
  ansible.builtin.systemd:
    name: 'overseerr'
    enabled: true
    daemon_reload: true
    state: 'restarted'
