---
###############################################################################
# Settings > Services > Radarr (settings.json > radarr)
###############################################################################
# Only v3+ servers are supported.
#
# HIGHLY RECOMMEND manual configuration of radarr settings then migrate values
# after initial installation.
#
# If you keep separate copies of non-4K and 4K media in your libraries, you
# will need to set up multiple radarr instances and link each of them to
# jellyseerr.
#
# Jellyseerr checks these linked servers to determine whether or not media has
# already been requested or is available, so two servers of each type are
# required if you keep separate non-4K and 4K copies of media.
#
# If you only maintain one copy of media, you can instead simply set up one
# server and set the 'Quality Profile' setting on a per-request basis.
#
# jellyseerr_cfg_radarr:
#     list of dict - Radarr servers to use.
#   - id: int - Jellyseerr radarr server order.
#         Default: 0.
#     name: str - Server name.
#     hostname: str - Server IP or DNS address.
#     port: int - Server port.
#           If radarr is behind a reverse proxy this is likely 443 (SSL).
#         Default: 7878.
#     api_key: str - Server API key.
#     use_ssl: bool - Use SSL with server.
#         Default: False.
#     base_url: str - Base URL path to access radarr.
#           Requires leading '/'.
#         Default: '' (disabled).
#     active_profile_id: int - Radarr quality profile ID.
#     active_profile_name: str - Radarr quality profile name.
#     active_directory: str - Radarr media directory.
#     tags: list of int - Tag ID's.
#         Default: [] (disabled).
#     is_4k: bool - 4k support.
#         Special Case:
#           * Only set to true if there are multiple servers defined and at
#             least one supports 4k.
#         Default: False.
#     is_default: bool - Default radarr server.
#         Default: True.
#     external_url: str - External URL to use.
#         Default: '' (disabled).
#     sync_enabled: bool - Enable scan/sync.
#         Default: True.
#     prevent_search: bool - Enable automatic search.
#         Default: True.
#     tag_requests: bool - Tag requests with user id/name.
#         Default: False.
#     override_rule: list of int - Override rule ID's.
#         Default: [] (disabled).
#     minimum_availability: str - Media availability.
#         Values:
#            released: Consider available when streaming or released to disc.
#           announced: Consider available when added to radarr.
#           inCinemas: Consider available when released to cinemas.
#         Default: 'released'.
#
# jellyseerr_cfg_radarr:
#   - id: 0
#     name: 'radarr'
#     hostname: '127.0.0.1'
#     port: 7878
#     api_key: '{{ vault_jellyseerr_cfg_radarr_api_key }}'
#     use_ssl: false
#     base_url: ''
#     active_profile_id: 1
#     active_profile_name: '1080p'
#     active_directory: '/data/media'
#     tags:
#       - 1
#       - 2
#     is_4k: false
#     is_default: true
#     external_url: ''
#     sync_enabled: true
#     prevent_search: true
#     tag_requests: false
#     override_rule:
#       - 1
#       - 2
#     minimum_availability: 'released'
#
# Default: [] (disabled).
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/settings/services
jellyseerr_cfg_radarr: []
