---
###############################################################################
# Settings > Services > Sonarr (settings.json > sonarr)
###############################################################################
# Only v3+ servers are supported.
#
# HIGHLY RECOMMEND manual configuration of sonarr settings then migrate values
# after initial installation.
#
# If you keep separate copies of non-4K and 4K media in your libraries, you
# will need to set up multiple sonarr instances and link each of them to
# jellyseerr.
#
# Jellyseerr checks these linked servers to determine whether or not media has
# already been requested or is available, so two servers of each type are
# required if you keep separate non-4K and 4K copies of media.
#
# If you only maintain one copy of media, you can instead simply set up one
# server and set the 'Quality Profile' setting on a per-request basis.
#
# jellyseerr_cfg_sonarr:
#     list of dict - Sonarr servers to use.
#   - id: int - Jellyseerr radarr server order.
#         Default: 0.
#     name: str - Server name.
#     hostname: str - Server IP or DNS address.
#     port: int - Server port.
#           If sonarr is behind a reverse proxy this is likely 443 (SSL).
#         Default: 8989.
#     api_key: str - Server API key.
#     use_ssl: bool - Use SSL with server.
#         Default: False.
#     base_url: str - Base URL path to access radarr.
#           Requires leading '/'.
#         Default: '' (disabled).
#     active_profile_id: int - Sonarr quality profile ID.
#     active_profile_name: str - Sonarr quality profile name.
#     active_directory: str - Sonarr media directory.
#     tags: list of int - Tag ID's.
#         Default: [] (disabled).
#     is_4k: bool - 4k support.
#         Default: False.
#     is_default: bool - Default radarr server.
#         Default: True.
#     external_url: str - External URL to use.
#         Default: '' (disabled).
#     sync_enabled: bool - Enable scan/sync.
#         Default: True.
#     prevent_search: bool - Enable automatic search.
#         Default: True.
#     tag_requests: bool - Tag requests with user id/name.
#         Default: False.
#     override_rule: list of int - Override rule ID's.
#         Default: [] (disabled).
#     series_type: str - Episode numbering scheme for all episodes.
#         Values:
#           standard: SXXEXX format.
#           daily: DATE format.
#           anime: Absolute episode number format.
#         Default: 'standard'.
#     anime_series_type: str - Episode numbering scheme for anime episodes.
#         Values:
#           standard: SXXEXX format.
#           daily: DATE format.
#           anime: Absolute episode number format.
#         Default: 'standard'.
#     active_anime_profile_id: int - Sonarr quality profile id.
#     active_anime_profile_name: str - Sonarr quality profile name.
#     active_anime_directory: str - Sonarr media directory.
#     active_anime_language_profile_id: int - Sonarr language profile id.
#         Default: 1 (english).
#     active_language_profile_id: int - Sonarr language profile id.
#         Default: 1 (english).
#     anime_tags: List of int - Tag ID's.
#         Default: [] (disabled).
#     enable_season_folders: bool - Use season folders.
#         Default: True.
#
# jellyseerr_cfg_sonarr:
#   - id: 0
#     name: 'sonarr'
#     hostname: '127.0.0.1'
#     port: 8989
#     api_key: '{{ vault_jellyseerr_cfg_sonarr_api_key }}'
#     use_ssl: false
#     base_url: ''
#     active_profile_id: 1
#     active_profile_name: '1080p'
#     active_directory: '/data/media'
#     tags:
#       - 1
#       - 2
#     is_4k: false
#     is_default: true
#     external_url: ''
#     sync_enabled: true
#     prevent_search: true
#     tag_requests: false
#     override_rule:
#       - 1
#       - 2
#     series_type: 'standard'
#     anime_series_type: 'standard'
#     active_language_profile_id: 1
#     active_anime_profile_id: 1
#     active_anime_profile_name: '1080p'
#     active_anime_directory: '/data/media'
#     active_anime_language_profile_id: 1
#     anime_tags:
#       - 1
#       - 2
#     enable_season_folders: true
#
# Default: [] (disabled).
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/settings/services
jellyseerr_cfg_sonarr: []
