---
###############################################################################
# Overseerr Service Config (overseerr.conf)
###############################################################################
# Externally stored service configuration for Overseerr to successfully start.
# Additional settings are stored in settings.json and the DB. WebUI locations
# are headers but all values are stored within config.xml.
#
# Documented usage here reflect code, installer, and WebUI analysis. These may
# change over time and should be re-validated from time to time.

# Bind Overseerr service to specified interface.
#
# Values:
#          '': bind to all available interfaces (default).
#        {IP}: bind to valid IP address ('127.0.0.1', '::', etc).
#   localhost: bind to localhost.
#
# Default: '' (all interfaces).
overseerr_config_bind_address: ''

# HTTP port. Default: 5055.
overseerr_config_port: 5055
