---
- name: 'Default | converge'
  hosts: all
  gather_facts: true
  tasks:
    - name: 'Default | converge | apply overseerr role to test systems'
      ansible.builtin.include_role:
        name: 'overseerr'
