---
# yamllint disable rule:line-length
# Confirm:
# * Overseerr built and running.
# * User is created.
# * second (build skip) run executes without error.
# * build cache is cleared.
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v1.33.2'
            asset: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/v1.33.2.tar.gz'
          - comment: 'no build'
            version: 'v1.33.2'
            asset: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/v1.33.2.tar.gz'
        overseerr_build_memory: 1500
        overseerr_users:
          - id: 1
            comment: 'test admin account'
            email: 'test@example.com'
            username: 'test'
            permissions: 2
            settings:
              watchlist_sync_movies: true
              watchlist_sync_tv: true
platforms:
  - name: 'overseerr-debian-12-default'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
