---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully.
#
# Tests:
# * Jellyseerr built and running.
# * Sqlite DB created.
# * Owner is created.
# * settings.json implicitly verified when service runs.
# * permissions propagated to all user data directories.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v2.7.3'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/v2.7.3.tar.gz"
              }}'
          - comment: 'no build'
            version: 'v2.7.3'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/v2.7.3.tar.gz"
              }}'
        jellyseerr_cfg_api_key:
          'NzJhZGFiODMtYjg4OC01Nzc1LWJhZjItODFhOTc1NDVhYjk5'
        jellyseerr_cfg_build_memory: 1500
        jellyseerr_srv_owner_password: 'testtest1'
platforms:
  - name: 'jellyseerr-debian-12-default'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '5055/tcp'
  - name: 'jellyseerr-debian-12-user_data'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
