---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | check 2.7.3'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache 2.7.3'
        test_dest: 'v2.7.3.tar.gz'
        test_url:
          'https://github.com/fallenbagel/jellyseerr/archive/refs/tags/v2.7.3.tar.gz'
        test_mode: '0640'
