---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | create cache'

    - name: 'Default | prepare | check 1.33.2'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache 1.33.2'
        test_dest: 'v1.33.2.tar.gz'
        test_url:
          'https://github.com/sct/overseerr/archive/refs/tags/v1.33.2.tar.gz'
        test_mode: '0640'
