---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | jellyseerr.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | jellyseerr.conf'
        test_src: 'files/jellyseerr.conf'
        test_file: '/etc/jellyseerr/jellyseerr.conf'
        test_owner: 'jellyseerr'
        test_group: 'jellyseerr'
        test_mode: '0640'
        test_diff: true
