---
###############################################################################
# Jellyfin/EMBY (settings.json > jellyfin)
###############################################################################
# Documented usage here reflect code, installer, and WebUI analysis. HIGHLY
# recommend to configure Jellyseerr in the WebUI and migrate settings here.
#
# set jellyseerr_cfg_media_server_type to set the correct media server to use.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/settings/mediaserver

# Jellyfin server friendly name. Default: ''.
jellyseerr_cfg_jellyfin_name: ''

# Jellyfin server IP or DNS name. Default: ''.
jellyseerr_cfg_jellyfin_ip: ''

# Jellyfin server port. Default: 32400.
jellyseerr_cfg_jellyfin_port: 8096

# Use HTTPS for Jellyfin connections.
#
# Self-signed certificates are not supported.
#
# Wildcard certificates will cause Jellyseerr to FAIL to connect with:
#
#  Hostname/IP does not match certificate's altnames:
#      IP: {IP} is not in the cert's list
#
# Default: False.
jellyseerr_cfg_jellyfin_use_ssl: false

# Jellyfin base server URL. Default: ''.
jellyseerr_cfg_jellyfin_url_base: ''

# Jellyfin external hostname. Default: ''.
jellyseerr_cfg_jellyfin_external_hostname: ''

# Jellyfin forgotten password URL. Default: ''.
jellyseerr_cfg_jellyfin_jellyfin_forgot_password_url: ''

# Jellyfin libraries to scan for existing titles.
#
# HIGHLY RECOMMEND manual configuration of Jellyfin settings (sync libraries,
# manual library scan) then migrate values after initial installation.
#
# jellyseerr_cfg_jellyfin_libraries:
#     list of dict - Jellyfin library settings.
#   - id: int - Jellyseerr order ID starting at 1.
#     name: str - Jellyfin library name.
#     enabled: bool - Enable scanning of Jellyfin library.
#         Default: True.
#     type: str - Jellyfin library type.
#         Values:
#           movie: movie (default).
#            show: series.
#         Default: 'movie'.
#     last_scan: int - unixtimestmp of last scan.
#         Default: 0 (EPOC - force scan).
#
# jellyseerr_cfg_jellyfin_libraries:
#   - id: 1
#     name: 'TV Shows'
#     enabled: true
#     type: 'show'
#     last_scan: 0
#   - id: 2
#     name: 'Movies'
#     enabled: true
#     type: 'movie'
#     last_scan: 0
#
# Default: [].
jellyseerr_cfg_jellyfin_libraries: []

# Jellyfin server ID used to claim the server. Default: ''.
jellyseerr_cfg_jellyfin_server_id: ''

# Jellyfin API key. Default: ''.
jellyseerr_cfg_jellyfin_api_key: ''
