---
###############################################################################
# Plex Media Server (settings.json > plex)
###############################################################################
# Documented usage here reflect code, installer, and WebUI analysis. HIGHLY
# recommend to configure Jellyseerr in the WebUI and migrate settings here.
#
# set jellyseerr_cfg_media_server_type to set the correct media server to use.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/settings/mediaserver

# Plex server friendly name. Default: ''.
jellyseerr_cfg_plex_name: ''

# Plex server IP or DNS name.
#
# You must use an externally accessible IP or DNS name to connect to plex and
# for plex users to import correctly otherwise the plex connection will fail
# and Users > 'Import Plex Users' will return no results. If you are using plex
# behind a proxy this is your external proxy address.
#
# Wildcard certificates will cause Jellyseerr to FAIL to connect with:
#
#  Hostname/IP does not match certificate's altnames:
#      IP: {IP} is not in the cert's list
#
# Load available servers and use the plex.direct local link.
#
# Enabling jellyseerr_cfg_new_plex_login will allow plex users with library
# access to sign-in without being imported.
#
# Default: ''.
jellyseerr_cfg_plex_ip: ''

# Plex server port. Default: 32400.
jellyseerr_cfg_plex_port: 32400

# Use HTTPS for plex connections.
#
# Self-signed certificates are not supported.
#
# Wildcard certificates will cause Jellyseerr to FAIL to connect with:
#
#  Hostname/IP does not match certificate's altnames:
#      IP: {IP} is not in the cert's list
#
# Load available servers and use the plex.direct local link.
#
# Default: False.
jellyseerr_cfg_plex_use_ssl: false

# Plex libraries to scan for existing titles.
#
# HIGHLY RECOMMEND manual configuration of plex settings (sync libraries,
# manual library scan) then migrate values after initial installation.
#
# jellyseerr_cfg_plex_libraries:
#     list of dict - plex library settings.
#   - id: int - Jellyseerr order ID starting at 1.
#     name: str - Plex library name.
#     enabled: bool - Enable scanning of plex library.
#         Default: True.
#     type: str - Plex library type.
#         Values:
#           movie: movie (default).
#            show: series.
#         Default: 'movie'.
#     last_scan: int - unixtimestmp of last scan.
#         Default: 0 (EPOC - force scan).
#
# jellyseerr_cfg_plex_libraries:
#   - id: 1
#     name: 'TV Shows'
#     enabled: true
#     type: 'show'
#     last_scan: 0
#   - id: 2
#     name: 'Movies'
#     enabled: true
#     type: 'movie'
#     last_scan: 0
#
# Default: [].
jellyseerr_cfg_plex_libraries: []

# Direct users to alternative plex web app player.
#
# The 'Play on Plex' button links to 'https://app.plex.tv/desktop' to play
# media from the configured server. This will force the use of your server
# instead. Incorrectly configuring this may result in a broken installation.
#
# Note that you will need to enter the full path to the web app (e.g.,
# https://plex.myawesomeserver.com/web).
#
# Default: '' (use 'https://app.plex.tv/desktop').
jellyseerr_cfg_plex_web_app_url: ''

# Plex machine ID used to claim the server (plex processed machine identifier).
#
# Found in Plex 'Preferences.xml' as 'ProcessedMachineIdentifier'.
#
# Default: ''.
jellyseerr_cfg_plex_machine_id: ''
