---
###############################################################################
# Settings > Notifications > Email (settings.json > email)
###############################################################################
# If jellyseerr_main_application_url=true Jellyseerr will explicitly set the
# origin server hostname when connecting to the SMTP host.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/email

# Enable notifications? Default: False.
jellyseerr_cfg_agents_email_enabled: false

# Require user email? Default: False.
jellyseerr_cfg_agents_email_user_email_required: false

# Sender name. Default: 'Jellyseerr'.
jellyseerr_cfg_agents_email_sender_name: 'Jellyseerr'

# Sender address.
#
# This may need to be an address you own depending on your email provider.
# Gmail requires this to be your actual email address.
#
# Default: ''.
jellyseerr_cfg_agents_email_email_from: ''

# SMTP host IP or hostname of your server. Default: ''.
jellyseerr_cfg_agents_email_smtp_host: ''

# SMTP port.
#
# Values:
#   465: For Implicit TLS.
#   587: For STARTTLS (default).
#     *: Custom port.
#
# Default: 587.
jellyseerr_cfg_agents_email_smtp_port: 587

# Encryption Method.
#
# Encryption is set by configuring three settings to represent one option.
# Highly recommend using STARTTLS or Implicit TLS if email is enabled.
#
# Values:
#                        None: jellyseerr_cfg_agents_email_secure: false
#                              jellyseerr_cfg_agents_email_ignore_tls: true
#                              jellyseerr_cfg_agents_email_require_tls: false
#   Use STARTTLS if available: jellyseerr_cfg_agents_email_secure: false
#                              jellyseerr_cfg_agents_email_ignore_tls: false
#                              jellyseerr_cfg_agents_email_require_tls: false
#         Always use STARTTLS: jellyseerr_cfg_agents_email_secure: false
#                              jellyseerr_cfg_agents_email_ignore_tls: false
#                              jellyseerr_cfg_agents_email_require_tls: true
#            Use Implicit TLS: jellyseerr_cfg_agents_email_secure: true
#                              jellyseerr_cfg_agents_email_ignore_tls: false
#                              jellyseerr_cfg_agents_email_require_tls: false
#
# Default: False, False, False (use STARTTLS if available).
jellyseerr_cfg_agents_email_secure: false
jellyseerr_cfg_agents_email_ignore_tls: false
jellyseerr_cfg_agents_email_require_tls: false

# Allow self-signed certificates? Default: False.
jellyseerr_cfg_agents_email_allow_self_signed: false

# SMTP username. Default: ''.
jellyseerr_cfg_agents_email_auth_user: ''

# SMTP password.
#
# If two-factor authentication is enabled, you may need to create an
# application password instead of using your account password.
#
# Set to a static value for redeployment.
#
# Default: '{RANDOM}' (randomly generated).
jellyseerr_cfg_agents_email_auth_pass: '{{
    lookup("ansible.builtin.password",
           "/dev/null",
           chars=["ascii_lowercase", "ascii_uppercase", "digits"],
           length=32)
  }}'

# PGP private key.
#
# Enables encrypting and signing of all email messages using OpenPGP.
#
# Individual users must also have their PGP public keys configured in their
# user settings in order for PGP encryption to be used in messages addressed to
# them.
#
# When configuring the PGP keys be sure to keep the entire contents of the key
# intact and use block.
#
# jellyseerr_cfg_agents_email_pgp_private_key:
#   -----BEGIN PGP PRIVATE KEY BLOCK-----
#   lFgEXEcE6RYJKwYBBAHaRw8BAQdArjWwk3FAqyiFbFBKT4TzXcVBqPTB3gmzlC/U
#   ...
#   Pnn+We1aTBhaGa86AQ==
#   -----END PGP PRIVATE KEY BLOCK-----
#
# Default: '' (disabled).
#
# Reference:
# * https://www.ietf.org/archive/id/draft-bre-openpgp-samples-01.html
jellyseerr_cfg_agents_email_pgp_private_key: ''

# PGP password used to sign encrypted email messages.
#
# Set to a static value for redeployment.
#
# Default: '{RANDOM}' (randomly generated).
jellyseerr_cfg_agents_email_pgp_password: '{{
    lookup("ansible.builtin.password",
           "/dev/null",
           chars=["ascii_lowercase", "ascii_uppercase", "digits"],
           length=32)
  }}'
