---
###############################################################################
# Settings > Notifications > Pushover (settings.json > pushover)
###############################################################################
# Users can optionally configure personal notifications in their user settings.
#
# User notifications are separate from system notifications, and the available
# notification types are dependent on user permissions.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/pushover

# Enable pushover notifications. Default: False.
jellyseerr_cfg_agents_pushover_enabled: false

# Application API token.
#
# Default: ''.
#
# Reference:
# * https://pushover.net/api#registration
jellyseerr_cfg_agents_pushover_access_token: ''

# User/group key.
#
# Set this to the user key for your Pushover account. Alternatively, you can
# set this to a group key to deliver notifications to multiple users.
#
# Default: ''.
#
# Reference:
# * https://pushover.net/api#identifiers
jellyseerr_cfg_agents_pushover_user_token: ''

# Notification sound.
#
# Default: '' (Device Default).
#
# Reference:
# * https://pushover.net/api#sounds
jellyseerr_cfg_agents_pushover_sound: ''

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# jellyseerr_cfg_agents_pushover_types: 322
#
# Default: 0.
jellyseerr_cfg_agents_pushover_types: 0
