---
###############################################################################
# Settings > Notifications > Pushbullet (settings.json > pushbullet)
###############################################################################
# Users can optionally configure personal notifications in their user settings.
#
# User notifications are separate from system notifications, and the available
# notification types are dependent on user permissions.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/pushbullet

# Enable notifications? Default: False.
jellyseerr_cfg_agents_pushbullet_enabled: false

# Access token.
#
# Default: ''.
#
# Reference:
# * https://www.pushbullet.com/#settings/account
jellyseerr_cfg_agents_pushbullet_access_token: ''

# Channel tag. Default: ''.
jellyseerr_cfg_agents_pushbullet_channel_tag: ''

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# jellyseerr_cfg_agents_pushbullet_types: 322
#
# Default: 0.
jellyseerr_cfg_agents_pushbullet_types: 0
