---
###############################################################################
# Settings > Notifications > Telegram (settings.json > telegram)
###############################################################################
# Users can optionally configure personal notifications in their user settings.
#
# User notifications are separate from system notifications, and the available
# notification types are dependent on user permissions.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/telegram

# Enable notifications? Default: False.
jellyseerr_cfg_agents_telegram_enabled: false

# Bot authorization token.
#
# Bot username should end with '_bot', and omit the '@' prefix. @BotFather will
# provide an authentication token at the end of the process. Use that token.
#
# Default: ''.
jellyseerr_cfg_agents_telegram_bot_api: ''

# Bot username. Default: ''.
jellyseerr_cfg_agents_telegram_bot_username: ''

# Chat ID.
#
# To obtain your chat ID create a new group chat and add '@get_id_bot'; issue
# the '/my_id' command. These generally start with a '-'.
#
# Default: ''.
jellyseerr_cfg_agents_telegram_chat_id: ''

# Thread/topic ID.
#
# If your group-chat has topics enabled, specify a thread/topic's ID here.
#
# Default: ''.
jellyseerr_cfg_agents_telegram_message_thread_id: ''

# Send notifications with no sound? Default: False.
jellyseerr_cfg_agents_telegram_send_silently: false

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# jellyseerr_cfg_agents_telegram_types: 322
#
# Default: 0.
jellyseerr_cfg_agents_telegram_types: 0
