---
###############################################################################
# Settings > Notifications > Webhook (settings.json > webhook)
###############################################################################
# The webhook notification agent enables you to send a custom JSON payload to
# any endpoint for specific notification events.
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/webhooks

# Enable notifications? Default: False.
jellyseerr_cfg_agents_webhook_enabled: false

# Webhook URL.
#
# jellyseerr_cfg_agents_webhook_json_payload will be the body of the request.
#
# Default: ''.
jellyseerr_cfg_agents_webhook_webhook_url: ''

# Authorization header.
#
# Authorization Header (optional) This is typically not needed. Please refer to
# your webhook provider's documentation for details.
#
# Default: ''.
jellyseerr_cfg_agents_webhook_auth_header: ''

# JSON payload (base64 encoded).
#
# See reference documentation for creating a json payload in jellyseerr. MUST
# BE BASE64 ENCODED!
#
# Default: 'Int9Ig==' ('{}' empty payload).
#
# Reference:
# * https://docs.jellyseerr.dev/using-jellyseerr/notifications/webhooks
jellyseerr_cfg_agents_webhook_json_payload: 'Int9Ig=='

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# jellyseerr_cfg_agents_webhook_types: 322
#
# Default: 0.
jellyseerr_cfg_agents_webhook_types: 0
