---
###############################################################################
# Jellyseerr User Options
###############################################################################

# Enable local sign-in?
#
# Allow users to sign in using their email address and password, instead of
# Media server OAuth. Users who have configured passwords will be allowed to
# sign in using their email address.
#
# When disabled Media server OAuth becomes the only sign-in option, and any
# local users will not be able to sign in to Jellyseerr.
#
# Default: True.
jellyseerr_cfg_local_login: true

# Enable media server (Plex) sign-in?
#
# Allow users to sign in using their media server OAuth account.
#
# When disabled local users become the only sign-in option, and any
# media server users will not be able to sign in to Jellyseerr.
#
# Default: True.
jellyseerr_cfg_media_server_login: true

# Enable new media server (Plex) sign-in?
#
# Allow Plex users to sign in without first being imported or added.
#
# Users with access to your Plex server will be able to sign in to Jellyseerr
# even if they have not yet been imported. Users will be automatically assigned
# the permissions configured in the Default Permissions setting
# jellyseerr_cfg_default_permissions upon first sign-in.
#
# Default: True.
jellyseerr_cfg_new_plex_login: true

# Global movie request limit (number of requests per period).
#
# Default: 0 (unlimited).
jellyseerr_cfg_default_quotas_movie_quota_limit: 0

# Global movie request limit (period in days). Default: 7 (unlimited).
jellyseerr_cfg_default_quotas_movie_quota_days: 7

# Global series request limit (number of requests per period).
#
# Default: 0 (unlimited).
jellyseerr_cfg_default_quotas_tv_quota_limit: 0

# Global series request limit (period in days). Default: 7 (unlimited).
jellyseerr_cfg_default_quotas_tv_quota_days: 7

# yamllint disable rule:line-length
# Default Permissions assigned to new users.
#
# Values are added cumulatively together to specify exact permissions.
#
# Values:
#           0: None.
#           2: Admin.
#           8: Manage users.
#          16: Manage requests.
#          32: Request (default).
#          64: Vote.
#         128: Auto approve.
#         256: Auto approve movie.
#         512: Auto approve tv.
#        1024: Request 4k.
#        2048: Request 4k movie.
#        4096: Request 4k tv.
#        8192: Request advanced.
#       16384: Request view.
#       32768: Auto approve 4k.
#       65536: Auto approve 4k movie.
#      131072: Auto approve 4k tv.
#      262144: Request movie.
#      524288: Request tv.
#     1048576: Manage issues.
#     2097152: View issues.
#     4194304: Create issues.
#     8388608: Auto request.
#    16777216: Auto request movie.
#    33554432: Auto request tv.
#    67108864: Recent view.
#   134217728: Watchlist view.
#
# User with 'request' and 'manage issues' permissions:
#
#   jellyseerr_cfg_default_permissions: 1048608
#
# Default: 32 (request).
#
# Reference:
# * https://github.com/fallenbagel/jellyseerr/blob/develop/server/lib/permissions.ts
# yamllint enable rule:line-length
jellyseerr_cfg_default_permissions: 32
